[WIP] EZEE-1710: Change Selenium version
ezsystems/ezpublish-docker pull request #59
Opened 2017-08-30 14:02 UTC by mnocon

> JIRA: [EZEE-1710](https://jira.ez.no/browse/EZEE-1710)

# Description

This PR introduces the same changes as in https://github.com/ezsystems/ezplatform/pull/203 to make sure our tests on Jenkins behave the same way as on Travis.

I'm marking it as WIP until the shm_size is decided in the original PR.

2017-08-31 12:39 UTC, mnocon commented
@vidarl @andrerom If I got everything right this PR should introduce the same changes to ezrobot that were done in https://github.com/ezsystems/ezplatform/pull/203

2017-08-31 12:52 UTC, vidarl requested changes

2017-08-31 12:52 UTC, vidarl commented on docker-compose_behat.yml.template
> +    shm_size: 256m
Indenting is wrong (one space too much)

2017-08-31 12:56 UTC, mnocon commented on docker-compose_behat.yml.template
> +    shm_size: 256m
Thanks, fixed

2017-08-31 13:00 UTC, vidarl commented
@micszo : Pinging you just in case as we have had quite a few issues with selenium/firefox in the past...

Looks fine to me.. Unless there are objections I purpose to merge after weekend ( Monday ). I should be able to dig into ezrobot if it by any chance causes problems

2017-08-31 13:05 UTC, micszo commented
@vidarl thanks. For me it's ok to take it easy.

2017-09-04 10:01 UTC, mnocon commented
@vidarl, @micszo do we give it a try? I guess the build won't be green (there might be changes to some tests needed, I'll handle it) but in general it should work.

2017-09-04 10:14 UTC, andrerom approved these changes

2017-09-04 10:34 UTC, vidarl approved these changes

2017-09-04 10:34 UTC, merged

2017-09-04 10:41 UTC, vidarl commented
merged, ezrobot should automatic pull the changes before running the next job